### ISSUE TITLE
Bower dependency of "bootstrap": "~3.3.5"

### ISSUE THREAD

**Issue by rafal-brize** [josemarluedke/ember-cli-daterangepicker#11]
Hello.

I was wondering if in change from 0.0.6 to 0.0.7 was intentional to include bootstrap as bower dependency. I've been using your datepicker without using bootstrap and now i cannot.

Especially including full bootstrap.css in index.js

   this.app.import(app.bowerDirectory + '/bootstrap/dist/css/bootstrap.css');

That came from a PR that's why i'm asking.

**Comment by josemarluedke** [comment]
@rafal-brize just pushed v0.0.9 to NPM removing bootstrap dependency. Thanks for pointing that out.
