### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by jamesdixon** [josemarluedke/ember-cli-daterangepicker#14]
Hi,

First, thanks for the component!

Is there any plans to upgrade to the 2.x version of bootstrap-daterangepicker? I noticed the current dependent version is very old in comparison.

Thanks,
James

**Comment by josemarluedke** [comment]
I can accept a PR with the upgrade if you would like to make the migration.

**Comment by malchak** [comment]
I can submit a PR for this.  Am running into the same issue.

**Comment by josemarluedke** [comment]
I would love that @malchak.

**Comment by malchak** [comment]
Okay, great.  See PR #18
