### ISSUE TITLE
can't find helper error

### ISSUE THREAD

**Issue by mlennie** [josemarluedke/ember-cli-daterangepicker#20]
Hi has this been updated for ember 2.0? `I'm seeing Uncaught Error: Assertion Failed: A helper named 'date-range-picker' could not be found`

When I use ember install:addon it tells me that that's depricated and that I should use ember install instead. Ok thanks!

**Comment by jamesdixon** [comment]
@mlennie need to install `bootstrap-daterangepicker` and `ember-moment` as well. It should probably be part of the dependencies to be automatically installed.
