### ISSUE TITLE
Tests!

### ISSUE THREAD

**Issue by josemarluedke** [josemarluedke/ember-cli-daterangepicker#35]
I would love to have tests for this addon. However, I'm not sure what to test and how. 

Anyone has some ideas or even be interested to implement some?

**Comment by gregjopa** [comment]
I think adding some integration tests would be a good start. Here are some examples: https://github.com/cibernox/ember-power-select/blob/master/tests/integration/components/power-select/general-behaviour-test.js

@supersabillon and I will work on adding some integration tests tomorrow.

**Comment by supersabillon** [comment]
https://github.com/supersabillon/ember-cli-daterangepicker/blob/tests/tests/integration/components/date-range-picker-test.js

Tests are still work in progress, but plan on completing on Monday and sending a PR.

**Comment by gregjopa** [comment]
:+1: the tests look good to me

**Comment by josemarluedke** [comment]
Closed by #36.
