### ISSUE TITLE
Issues including as a dependency in addon

### ISSUE THREAD

**Issue by trumb1mj** [josemarluedke/ember-cli-daterangepicker#50]
When I try to include `ember-cli-daterangepicker` within my addon repo, I get an error on server run:

`Cannot read property 'import' of undefined
TypeError: Cannot read property 'import' of undefined
    at Class.module.exports.included (/Users/mtrumbell/projects/cloud-services/release-clean/tmp2/optionshop-webapp/node_modules/city-trader-ember-components/node_modules/ember-cli-daterangepicker/index.js:9:13)`

It seems related to this:  https://github.com/ember-cli/ember-cli/issues/3718#issuecomment-182526160

I ended up trying this and it worked (index.js):

```
/* jshint node: true */
'use strict';

module.exports = {
  name: 'ember-cli-daterangepicker',

  included: function(app) {

    this._super.included.apply(this, arguments);

    if (typeof app.import !== 'function' && app.app) {
      app = app.app;
    }

    app.import(app.bowerDirectory + '/moment/moment.js');
    app.import(app.bowerDirectory + '/bootstrap-daterangepicker/daterangepicker.js');
    app.import(app.bowerDirectory + '/bootstrap-daterangepicker/daterangepicker.css');
  }
};
```

**Comment by josemarluedke** [comment]
Do you mind opening a PR with a fix for this? Thanks.

**Comment by vlascik** [comment]
This fix is not needed anymore, ember-cli includes fixed nested import since 2.5.x i think, there is a pollyfil for older versions.

**Comment by josemarluedke** [comment]
@trumb1mj are you still having this problem?

**Comment by makepanic** [comment]
This is still an issue for consuming ember-cli-daterangepicker in addons.
The solution is to use `this.import` instead of `app.import`.

There exists a polyfill to implement this.import for older cli versions: https://github.com/ember-cli/ember-cli-import-polyfill

I'll create a PR to do that.

**Comment by eagle-dan1349** [comment]
Guys, this one is still an issue when using in addons.
Seems like changes from pull-request got lost.
Can you take a look?

**Comment by josemarluedke** [comment]
I haven’t released a new version yet containing these changes . I will let you know when that happens.
