### ISSUE TITLE
Upgrade the version of dependency 'ember-cli-moment-shim'?

### ISSUE THREAD

**Issue by shijistar** [josemarluedke/ember-cli-daterangepicker#57]
Is it possible to upgrade dependency 'ember-cli-moment-shim' to latest version? The major version is v2 right now.
We included 'ember-cli-moment-shim' inside the addon, but I'm also using other addons such as 'ember-moment' which installs it in the main project in blueprints. The problem is if I upgraded 'ember-cli-moment-shim' in my project to v2.2.1, I found the 'moment.js' was imported to vendor.js twice! one was debug version, while another was minified version.
After some analysis I think I found the reason. In version 2.2.1, the moment.js was imported in this way,
```js
app.import({
   development: vendor + '/moment/moment.js',
   production: vendor + '/moment/min/moment.min.js'
}, { prepend: true });
```
and since v2, 'moment' and 'moment-timezone' were included inside the addon.
But in v1 (inside ember-cli-daterangepicker), it was imported in this way,
```js
app.import(vendor + '/moment/min/moment.min.js', { prepend: true });
```
So I think that the debug version was imported by v2.2.1, while the minified version was imported by v1, although I'm running in 'development' environment.
So I wonder whether is it possible to upgrade 'ember-cli-moment-shim'' to latest version, or move it out of the addon? Thank you very much!

**Comment by josemarluedke** [comment]
Thank you for reporting this. 

Yes, we definably should upgrade `ember-cli-moment-shim`. 

@shijistar would you be up to get a PR making this upgrade? We probably could remove moment, moment-timezone deps from `package.json` and make `ember-cli-moment-shim` a peer dependency. In addition, we should create a blueprint in which would add `ember-cli-moment-shim` to the user's `package.json` when installing this addon.

**Comment by msalahz** [comment]
Hi Guys, Any updates ?

**Comment by shijistar** [comment]
I will make a PR.

**Comment by josemarluedke** [comment]
Thanks to @shijistar we have this completed. I just pushed v0.3.0 to NPM.
