### ISSUE TITLE
Time Is Not Updated after click on Apply

### ISSUE THREAD

**Issue by vishusharmagit** [josemarluedke/ember-cli-daterangepicker#59]
I want to allow user to select time as well with date.
But, Clicking on apply only updated date not time.

**Comment by josemarluedke** [comment]
Could you create a reproduction of this problem using ember-twiddle.com ?

**Comment by vishusharmagit** [comment]
It working fine. I updated my code.
Thanks

**Comment by zardaloop** [comment]
@vishusharmagit  I am having the same issue, what did you change to fix it?

**Comment by vishusharmagit** [comment]
@zardaloop For this issue.

I added "**timePicker=true**" config property in it.
Also, add following two config property : 

**format='MMM D, YYYY h:mm A'
serverFormat='MMM D, YYYY h:mm A'**

These two properties help in view mode in my case.

**Comment by zardaloop** [comment]
@vishusharmagit perfect .. thanks. It did the trick. 😊

**Comment by vishusharmagit** [comment]
Welcome @zardaloop , 😊
