### ISSUE TITLE
Update addon to use ember-cli0.2.7

### ISSUE THREAD

**Issue by malchak** [josemarluedke/ember-cli-daterangepicker#8]
Currently this addon runs on `ember-cli v0.1.7`.  This release this contains the `glob` dependency that breaks the dummy app when running `ember serve`.  Are there plans to update this addon to `ember-cli v0.2.7`?

**Comment by josemarluedke** [comment]
Hello @malchak. I would love to see a PR upgrading ember-cli. Any chance you can work on that?

**Comment by malchak** [comment]
@josemarluedke I can, no problem.  Also, I've noticed that the logic for building the plugin is inside of the `/app` directory, instead of the `/addon` directory.  I can also work on moving the component logic inside `/addon` to comply with the Ember.js community conventions.  What do you think?

**Comment by josemarluedke** [comment]
That would be great! Thank you @malchak.

**Comment by malchak** [comment]
@josemarluedke PR sent.  It only includes the ember-cli and hence the ember version bumps.  I'm working on another for an optional serverFormat param.
